export const ActionTypes = {
    FETCH_COUNCILLORS: 'FETCH_COUNCILLORS',
    FETCH_COUNCILLORS_COMPLETE: 'FETCH_COUNCILLORS_COMPLETE',
    FETCH_COUNCILLORS_ERROR: 'FETCH_COUNCILLORS_ERROR',
    SORT_COUNCILLORS: 'SORT_COUNCILLORS',
    FILTER_COUNCILLORS: 'FILTER_COUNCILLORS',
    RESET_FILTERS_COUNCILLORS: 'RESET_FILTERS_COUNCILLORS',
};
